packages:
  - "apps/*"
  - "libs/*"
  - "libs/@wingcloud/*"
  - "tools/*"
  - "docs/docs"
  - "apps/wing-console/packages/*"
  - "apps/wing-console/console/*"
  - "apps/wing-console/tools/*"
  - "tests/*"
  - "examples/*"
  - "apps/jsii-docgen/test/__fixtures__/**"
